"""Add Boon model for tracking favors

Revision ID: 120defe146e7
Revises: 7711f72054f3
Create Date: 2026-02-13 13:32:12.542736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120defe146e7'
down_revision: Union[str, Sequence[str], None] = '7711f72054f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boons',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('holder_id', sa.String(length=36), nullable=False),
    sa.Column('other_character_id', sa.String(length=36), nullable=True),
    sa.Column('boon_type', sa.String(length=50), nullable=False),
    sa.Column('is_owed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boon_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_boons_game_id_games')),
    sa.ForeignKeyConstraint(['holder_id'], ['characters.id'], name=op.f('fk_boons_holder_id_characters')),
    sa.ForeignKeyConstraint(['other_character_id'], ['characters.id'], name=op.f('fk_boons_other_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boons'))
    )
    op.create_index(op.f('ix_boons_game_id'), 'boons', ['game_id'], unique=False)
    op.create_index(op.f('ix_boons_holder_id'), 'boons', ['holder_id'], unique=False)
    op.create_index(op.f('ix_boons_other_character_id'), 'boons', ['other_character_id'], unique=False)
    op.create_table('boon_history',
    sa.Column('boon_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boon_id'], ['boons.id'], name=op.f('fk_boon_history_boon_id_boons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boon_history'))
    )
    op.create_index(op.f('ix_boon_history_boon_id'), 'boon_history', ['boon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boon_history_boon_id'), table_name='boon_history')
    op.drop_table('boon_history')
    op.drop_index(op.f('ix_boons_other_character_id'), table_name='boons')
    op.drop_index(op.f('ix_boons_holder_id'), table_name='boons')
    op.drop_index(op.f('ix_boons_game_id'), table_name='boons')
    op.drop_table('boons')
    # ### end Alembic commands ###
