"""Initial migration with all models

Revision ID: 7711f72054f3
Revises: 
Create Date: 2026-02-13 13:12:40.518744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7711f72054f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chronicle_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('usual_place', sa.String(length=255), nullable=True),
    sa.Column('usual_time', sa.String(length=100), nullable=True),
    sa.Column('extended_health', sa.Boolean(), nullable=False),
    sa.Column('enforce_history', sa.Boolean(), nullable=False),
    sa.Column('link_trait_maxes', sa.Boolean(), nullable=False),
    sa.Column('random_traits', sa.String(length=255), nullable=False),
    sa.Column('st_comment_start', sa.String(length=50), nullable=False),
    sa.Column('st_comment_end', sa.String(length=50), nullable=False),
    sa.Column('file_format_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('calendar',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_calendar_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar'))
    )
    op.create_index(op.f('ix_calendar_game_id'), 'calendar', ['game_id'], unique=False)
    op.create_table('health_levels',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('is_abbreviated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_health_levels_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_levels'))
    )
    op.create_index(op.f('ix_health_levels_game_id'), 'health_levels', ['game_id'], unique=False)
    op.create_table('items',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=50), nullable=True),
    sa.Column('damage_amount', sa.Integer(), nullable=False),
    sa.Column('concealability', sa.String(length=50), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('powers', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_items_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_game_id'), 'items', ['game_id'], unique=False)
    op.create_table('output_templates',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_output_templates_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_output_templates'))
    )
    op.create_index(op.f('ix_output_templates_game_id'), 'output_templates', ['game_id'], unique=False)
    op.create_table('players',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pp_unspent', sa.Integer(), nullable=False),
    sa.Column('pp_earned', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_players_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_table('plots',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_plots_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plots'))
    )
    op.create_index(op.f('ix_plots_game_id'), 'plots', ['game_id'], unique=False)
    op.create_table('saved_queries',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_data', sa.Text(), nullable=False),
    sa.Column('sort_field', sa.String(length=100), nullable=True),
    sa.Column('sort_ascending', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_saved_queries_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queries'))
    )
    op.create_index(op.f('ix_saved_queries_game_id'), 'saved_queries', ['game_id'], unique=False)
    op.create_table('xp_awards',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('pp_amount', sa.Integer(), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_xp_awards_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_awards'))
    )
    op.create_index(op.f('ix_xp_awards_game_id'), 'xp_awards', ['game_id'], unique=False)
    op.create_table('characters',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('race_type', sa.String(length=50), nullable=False),
    sa.Column('is_npc', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('xp_unspent', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('health_levels', sa.JSON(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('narrator', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_characters_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_characters_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    op.create_index(op.f('ix_characters_game_id'), 'characters', ['game_id'], unique=False)
    op.create_index(op.f('ix_characters_player_id'), 'characters', ['player_id'], unique=False)
    op.create_index(op.f('ix_characters_race_type'), 'characters', ['race_type'], unique=False)
    op.create_table('player_point_history',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unspent_after', sa.Integer(), nullable=True),
    sa.Column('earned_after', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_point_history_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_point_history'))
    )
    op.create_table('actions',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('action_date', sa.String(length=10), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('unused', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_actions_character_id_characters')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_actions_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_action_date'), 'actions', ['action_date'], unique=False)
    op.create_index(op.f('ix_actions_character_id'), 'actions', ['character_id'], unique=False)
    op.create_index(op.f('ix_actions_game_id'), 'actions', ['game_id'], unique=False)
    op.create_table('character_items',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_items_character_id_characters')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_character_items_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_items'))
    )
    op.create_index(op.f('ix_character_items_character_id'), 'character_items', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_items_item_id'), 'character_items', ['item_id'], unique=False)
    op.create_table('experience_history',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('unspent_after', sa.Integer(), nullable=True),
    sa.Column('earned_after', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_experience_history_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_history'))
    )
    op.create_index(op.f('ix_experience_history_character_id'), 'experience_history', ['character_id'], unique=False)
    op.create_table('locations',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('access', sa.Text(), nullable=True),
    sa.Column('affinity', sa.String(length=100), nullable=True),
    sa.Column('totem', sa.String(length=255), nullable=True),
    sa.Column('security_traits', sa.Integer(), nullable=False),
    sa.Column('security_retests', sa.Integer(), nullable=False),
    sa.Column('gauntlet_shroud', sa.String(length=50), nullable=True),
    sa.Column('where_description', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('security_description', sa.Text(), nullable=True),
    sa.Column('umbra_description', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_locations_game_id_games')),
    sa.ForeignKeyConstraint(['owner_id'], ['characters.id'], name=op.f('fk_locations_owner_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_game_id'), 'locations', ['game_id'], unique=False)
    op.create_index(op.f('ix_locations_owner_id'), 'locations', ['owner_id'], unique=False)
    op.create_table('rotes',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('character_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spheres', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_rotes_character_id_characters')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rotes_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rotes'))
    )
    op.create_index(op.f('ix_rotes_character_id'), 'rotes', ['character_id'], unique=False)
    op.create_index(op.f('ix_rotes_game_id'), 'rotes', ['game_id'], unique=False)
    op.create_table('rumors',
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rumor_date', sa.String(length=10), nullable=False),
    sa.Column('target_character_id', sa.String(length=36), nullable=True),
    sa.Column('target_race', sa.String(length=50), nullable=True),
    sa.Column('target_group', sa.String(length=100), nullable=True),
    sa.Column('target_influence', sa.String(length=100), nullable=True),
    sa.Column('distributed_to', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rumors_game_id_games')),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], name=op.f('fk_rumors_target_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rumors'))
    )
    op.create_index(op.f('ix_rumors_game_id'), 'rumors', ['game_id'], unique=False)
    op.create_index(op.f('ix_rumors_rumor_date'), 'rumors', ['rumor_date'], unique=False)
    op.create_index(op.f('ix_rumors_target_character_id'), 'rumors', ['target_character_id'], unique=False)
    op.create_table('traits',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('display_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_traits_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traits'))
    )
    op.create_index(op.f('ix_traits_category'), 'traits', ['category'], unique=False)
    op.create_index(op.f('ix_traits_character_id'), 'traits', ['character_id'], unique=False)
    op.create_table('character_locations',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_locations_character_id_characters')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_character_locations_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_locations'))
    )
    op.create_index(op.f('ix_character_locations_character_id'), 'character_locations', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_locations_location_id'), 'character_locations', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_locations_location_id'), table_name='character_locations')
    op.drop_index(op.f('ix_character_locations_character_id'), table_name='character_locations')
    op.drop_table('character_locations')
    op.drop_index(op.f('ix_traits_character_id'), table_name='traits')
    op.drop_index(op.f('ix_traits_category'), table_name='traits')
    op.drop_table('traits')
    op.drop_index(op.f('ix_rumors_target_character_id'), table_name='rumors')
    op.drop_index(op.f('ix_rumors_rumor_date'), table_name='rumors')
    op.drop_index(op.f('ix_rumors_game_id'), table_name='rumors')
    op.drop_table('rumors')
    op.drop_index(op.f('ix_rotes_game_id'), table_name='rotes')
    op.drop_index(op.f('ix_rotes_character_id'), table_name='rotes')
    op.drop_table('rotes')
    op.drop_index(op.f('ix_locations_owner_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_game_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_experience_history_character_id'), table_name='experience_history')
    op.drop_table('experience_history')
    op.drop_index(op.f('ix_character_items_item_id'), table_name='character_items')
    op.drop_index(op.f('ix_character_items_character_id'), table_name='character_items')
    op.drop_table('character_items')
    op.drop_index(op.f('ix_actions_game_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_character_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_date'), table_name='actions')
    op.drop_table('actions')
    op.drop_table('player_point_history')
    op.drop_index(op.f('ix_characters_race_type'), table_name='characters')
    op.drop_index(op.f('ix_characters_player_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_game_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_xp_awards_game_id'), table_name='xp_awards')
    op.drop_table('xp_awards')
    op.drop_index(op.f('ix_saved_queries_game_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_plots_game_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_output_templates_game_id'), table_name='output_templates')
    op.drop_table('output_templates')
    op.drop_index(op.f('ix_items_game_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_health_levels_game_id'), table_name='health_levels')
    op.drop_table('health_levels')
    op.drop_index(op.f('ix_calendar_game_id'), table_name='calendar')
    op.drop_table('calendar')
    op.drop_table('games')
    # ### end Alembic commands ###
